name: Build RSS & Package site files (from repo) + optional notify

on:
  push:
    branches: [ main ]
    paths:
      - 'sitemap.xml'
      - 'resources.html'
      - 'robots.txt'
      - 'README.md'
      - '.github/workflows/site-pack.yml'
  workflow_dispatch:
    inputs:
      notify_after_deploy:
        description: '运维已部署到官网后，是否通知 Hub + Ping 搜索引擎？(true/false)'
        required: false
        default: 'false'

permissions:
  contents: write

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sanity check required files
        run: |
          for f in sitemap.xml resources.html robots.txt; do
            [ -f "$f" ] || { echo "::error file=$f::File not found"; exit 1; }
          done

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate rss.xml from local sitemap.xml
        run: |
          python - <<'PY'
import datetime, xml.etree.ElementTree as ET
from urllib.parse import urlparse
from xml.sax.saxutils import escape

SITEMAP_PATH = "sitemap.xml"
RSS_PUBLIC_URL = "https://www.cfiee-edu.com/rss.xml"   # 线上访问地址
HUB_URL = "https://pubsubhubbub.appspot.com/"

root = ET.parse(SITEMAP_PATH).getroot()
ns = {"sm":"http://www.sitemaps.org/schemas/sitemap/0.9"}
urls=[]
for u in root.findall("sm:url", ns):
    loc = (u.findtext("sm:loc", default="", namespaces=ns) or "").strip()
    lastmod = (u.findtext("sm:lastmod", default="", namespaces=ns) or "").strip()
    if loc:
        urls.append((loc,lastmod))

tz = datetime.timezone(datetime.timedelta(hours=8))
now = datetime.datetime.now(tz)
now_rfc2822 = now.strftime("%a, %d %b %Y %H:%M:%S %z")

def to_rfc2822(d):
    try:
        dt = datetime.datetime.strptime(d[:10], "%Y-%m-%d").replace(tzinfo=tz)
    except Exception:
        dt = now
    return dt.strftime("%a, %d %b %Y %H:%M:%S %z")

items=[]
for loc,lastmod in urls[:200]:
    title = (urlparse(loc).path.strip('/') or 'Home').title()
    pub = to_rfc2822(lastmod)
    items.append(f"""  <item>
    <title>{escape(title)}</title>
    <link>{escape(loc)}</link>
    <guid isPermaLink="true">{escape(loc)}</guid>
    <pubDate>{pub}</pubDate>
    <description>Change the status quo — economic education can change lives.</description>
  </item>""")

rss=f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>CFIEE · Council for International Economic Education</title>
    <link>https://www.cfiee-edu.com/</link>
    <description>Change the status quo — economic education can change lives.</description>
    <language>de</language>
    <lastBuildDate>{now_rfc2822}</lastBuildDate>
    <atom:link href="{RSS_PUBLIC_URL}" rel="self" type="application/rss+xml" />
    <atom:link href="{HUB_URL}" rel="hub" />
{chr(10).join(items)}
  </channel>
</rss>"""

open("rss.xml","w",encoding="utf-8").write(rss)
print("rss.xml generated with", len(items), "items")
PY

      - name: Prepare dist folder (include README if exists)
        run: |
          mkdir -p dist
          cp -f sitemap.xml resources.html robots.txt rss.xml dist/
          [ -f README.md ] && cp -f README.md dist/ || true
          ls -l dist

      - name: Upload artifacts (single files)
        uses: actions/upload-artifact@v4
        with:
          name: site-files
          path: |
            dist/rss.xml
            dist/sitemap.xml
            dist/resources.html
            dist/robots.txt
            dist/README.md
          if-no-files-found: ignore
          retention-days: 30

      - name: Create and upload ZIP
        run: |
          cd dist
          zip -9r ../site-files-pack.zip ./*
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: site-files-pack
          path: site-files-pack.zip
          retention-days: 30

  notify-after-deploy:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.notify_after_deploy == 'true' }}
    needs: build-and-package
    runs-on: ubuntu-latest
    steps:
      - name: Notify PubSubHubbub Hub (assumes rss.xml is live online)
        run: |
          curl -sS -X POST https://pubsubhubbub.appspot.com/notify \
               --data-urlencode "hub.mode=publish" \
               --data-urlencode "hub.url=https://www.cfiee-edu.com/rss.xml"
          echo "Notified Hub."

      - name: Ping Google & Bing with sitemap (assumes sitemap.xml is live)
        run: |
          curl -s "https://www.google.com/ping?sitemap=https://www.cfiee-edu.com/sitemap.xml"
          curl -s "https://www.bing.com/ping?sitemap=https://www.cfiee-edu.com/sitemap.xml"
          echo "Pinged Google & Bing."
