name: Notify Hub + Google + Bing + IndexNow (manual all-in-one)

on:
  workflow_dispatch:
    inputs:
      run_hub:
        description: 'Notify PubSubHubbub Hub? (true/false)'
        required: true
        default: 'true'
      rss_urls:
        description: 'One or more public feed URLs to notify (one per line).'
        required: false
        default: 'https://www.cfiee-edu.com/rss.xml'
      hub_url:
        description: 'Hub endpoint'
        required: false
        default: 'https://pubsubhubbub.appspot.com/notify'

      sitemap_url:
        description: 'Public sitemap URL to ping'
        required: false
        default: 'https://www.cfiee-edu.com/sitemap.xml'
      run_google:
        description: 'Ping Google? (true/false)'
        required: true
        default: 'true'
      run_bing:
        description: 'Ping Bing? (true/false)'
        required: true
        default: 'true'

      run_indexnow:
        description: 'Notify Bing IndexNow? (true/false)'
        required: true
        default: 'true'
      indexnow_key:
        description: 'Your IndexNow key (must also exist as TXT file in site root)'
        required: false
        default: '9e4e22c8217239645e4f6718bddfdc1c'
      indexnow_endpoint:
        description: 'IndexNow endpoint'
        required: false
        default: 'https://api.indexnow.org/indexnow'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Show inputs
        run: |
          echo "Hub: ${{ inputs.run_hub }}"
          echo "RSS: ${{ inputs.rss_urls }}"
          echo "Google: ${{ inputs.run_google }}"
          echo "Bing: ${{ inputs.run_bing }}"
          echo "IndexNow: ${{ inputs.run_indexnow }}"
          echo "Sitemap: ${{ inputs.sitemap_url }}"

      - name: Notify Hub
        if: ${{ inputs.run_hub == 'true' }}
        run: |
          set -euo pipefail
          HUB="${{ inputs.hub_url }}"
          for URL in ${{ inputs.rss_urls }}; do
            echo "Notifying hub for $URL"
            curl -sS -X POST "$HUB"               --data-urlencode "hub.mode=publish"               --data-urlencode "hub.url=${URL}"
          done

      - name: Ping Google
        if: ${{ inputs.run_google == 'true' }}
        run: |
          set -euo pipefail
          SITEMAP="${{ inputs.sitemap_url }}"
          curl -sS "https://www.google.com/ping?sitemap=${SITEMAP}" || echo "Google ping may not return 200"

      - name: Ping Bing
        if: ${{ inputs.run_bing == 'true' }}
        run: |
          set -euo pipefail
          SITEMAP="${{ inputs.sitemap_url }}"
          curl -sS "https://www.bing.com/ping?sitemap=${SITEMAP}"

      - name: Notify IndexNow
        if: ${{ inputs.run_indexnow == 'true' }}
        run: |
          set -euo pipefail
          SITEMAP="${{ inputs.sitemap_url }}"
          KEY="${{ inputs.indexnow_key }}"
          ENDPOINT="${{ inputs.indexnow_endpoint }}"
          BODY=$(jq -nc --arg host "$(echo $SITEMAP | awk -F/ '{print $3}')"                         --arg key "$KEY"                         --argjson urls "[\"$SITEMAP\"]"                         '{host:$host, key:$key, urlList:$urls}')
          echo "Sending IndexNow notification"
          curl -sS -X POST -H "Content-Type: application/json" --data "$BODY" "$ENDPOINT"
