name: Build RSS & Package site files (from repo) + optional notify

on:
  push:
    branches: [ main ]
    paths:
      - 'sitemap.xml'
      - 'resources.html'
      - 'robots.txt'
      - 'README.md'
      - '.github/workflows/site-pack.yml'
  workflow_dispatch:
    inputs:
      notify_after_deploy:
        description: '运维已部署到官网后，是否通知 Hub + Ping 搜索引擎？(true/false)'
        required: false
        default: 'false'

permissions:
  contents: write

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sanity check required files
        run: |
          for f in sitemap.xml resources.html robots.txt; do
            [ -f "$f" ] || { echo "::error file=$f::File not found"; exit 1; }
          done

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate rss.xml from local sitemap.xml
        run: |
          python - <<'PY'
import datetime, xml.etree.ElementTree as ET
from urllib.parse import urlparse
from xml.sax.saxutils import escape

SITEMAP_PATH = "sitemap.xml"
RSS_PUBLIC_URL = "https://www.cfiee-edu.com/rss.xml"
HUB_URL = "https://pubsubhubbub.appspot.com/"

root = ET.parse(SITEMAP_PATH).getroot()
ns = {"sm":"http://www.sitemaps.org/schemas/sitemap/0.9"}
urls=[]
for u in root.findall("sm:url", ns):
    loc = (u.findtext("sm:loc", default="", namespaces=ns) or "").strip()
    lastmod = (u.findtext("sm:lastmod", default="", namespaces=ns) or "").strip()
    if loc:
        urls.append((loc,lastmod))

tz = datetime.timezone(datetime.t
